export default {
  "login": "mdobaid311",
  "id": 81803774,
  "node_id": "MDQ6VXNlcjgxODAzNzc0",
  "avatar_url": "https://avatars.githubusercontent.com/u/81803774?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/mdobaid311",
  "html_url": "https://github.com/mdobaid311",
  "followers_url": "https://api.github.com/users/mdobaid311/followers",
  "following_url": "https://api.github.com/users/mdobaid311/following{/other_user}",
  "gists_url": "https://api.github.com/users/mdobaid311/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/mdobaid311/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/mdobaid311/subscriptions",
  "organizations_url": "https://api.github.com/users/mdobaid311/orgs",
  "repos_url": "https://api.github.com/users/mdobaid311/repos",
  "events_url": "https://api.github.com/users/mdobaid311/events{/privacy}",
  "received_events_url": "https://api.github.com/users/mdobaid311/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mohammed obaid",
  "company": null,
  "blog": "",
  "location": "Hyderabad,India",
  "email": null,
  "hireable": null,
  "bio": "Turning coffee into code.",
  "twitter_username": "mdobaid311",
  "public_repos": 32,
  "public_gists": 0,
  "followers": 6,
  "following": 8,
  "created_at": "2021-04-02T09:04:52Z",
  "updated_at": "2021-12-25T14:34:56Z"
}